<?php

/*
 * This work is licensed under
 * the Creative Commons Attribution 4.0 International License.
 * To view a copy of this license, visit
 * http://creativecommons.org/licenses/by/4.0/.
 */

$config = [];

/*
  |-----------------------------------------------------------------------------
  | Base Site URL
  |-----------------------------------------------------------------------------
  |
  | URL to your website root. This will be your base URL,
  | WITH a trailing slash: http://example.com/
  |
  | If it is not set, then Beerawecka will try to auto detect the URL using
  | $_SERVER informations.
  |
  | WARNING: You SHOULD set this value for security!
  |
 */
$config['base_url'] = '';

/*
  |-----------------------------------------------------------------------------
  | Index File
  |-----------------------------------------------------------------------------
  |
  | Typically this will be your index.php file, unless you've renamed it to
  | something else. If you are using URL rewriting set this variable to empty.
  |
 */
$config['index_page'] = 'index.php';

/*
  |-----------------------------------------------------------------------------
  | URL suffix
  |-----------------------------------------------------------------------------
  |
  | This option allows you to add a suffix to all URLs generated by the Input class
 */
$config['url_suffix'] = '';

/*
  |-----------------------------------------------------------------------------
  | Allowed URL Characters
  |-----------------------------------------------------------------------------
  |
  | This lets you specify which characters are permitted within your URLs.
  |
  | As a security measure you are STRONGLY encouraged to restrict URLs to
  | as few characters as possible.
  | By default only these are allowed: a-z 0-9~%.:_\-/
  |
  | The configured value is actually a regular expression character group
  | and it will be executed as: ! preg_match('/^[<permitted_uri_chars>]+$/i
  |
 */
$config['uri_chars'] = 'a-z 0-9~%.:_\-/';

/*
  |-----------------------------------------------------------------------------
  | Default Character Set
  |-----------------------------------------------------------------------------
  |
  | Set up PHP for working with Unicode data
  |
 */
$config['utf8'] = TRUE;

/*
  |-----------------------------------------------------------------------------
  | Default Character Set
  |-----------------------------------------------------------------------------
  |
  | Set locale information for all settings excepted for decimal separator
  |
 */
$config['locale'] = 'en_US.utf8';

return $config;

/* End of file */